precision highp float;
precision highp int;
uniform mat4 modelMatrix;
uniform mat4 viewMatrix;
uniform mat4 projectionMatrix;
uniform vec4 _RainbowTintMask_ST;
uniform vec4 _RainbowTex_ST;
uniform vec4 _RainbowOutlineTex_ST;
uniform vec4 _RainbowBGTex_ST;
vec2 pcrRainbowTintUv;
vec2 pcrRainbowUv;
vec2 pcrRainbowOutlineUv;
vec2 pcrRainbowBgUv;
in vec3 position;
out vec3 vs_TEXCOORD1;
out vec4 vs_TEXCOORD0;
in vec2 uv;
in vec3 normal;
out vec3 vs_TEXCOORD2;
out vec4 vs_TEXCOORD3;
out vec4 vs_TEXCOORD4;
vec4 _9;
vec4 _44;
float _138;

void main()
{
    vec4 _11 = vec4(position, 1.0);
    vec2 _99 = uv;
    vec3 _116 = normal;
    mat4 _ObjectToWorld = modelMatrix;
    mat4 _WorldToObject = inverse(modelMatrix);
    mat4 _ViewProjection = projectionMatrix * viewMatrix;
    _9 = _11.yyyy * _ObjectToWorld[1];
    _9 = (_ObjectToWorld[0] * _11.xxxx) + _9;
    _9 = (_ObjectToWorld[2] * _11.zzzz) + _9;
    _44 = _9 + _ObjectToWorld[3];
    vs_TEXCOORD1 = (_ObjectToWorld[3].xyz * _11.www) + _9.xyz;
    _9 = _44.yyyy * _ViewProjection[1];
    _9 = (_ViewProjection[0] * _44.xxxx) + _9;
    _9 = (_ViewProjection[2] * _44.zzzz) + _9;
    _9 = (_ViewProjection[3] * _44.wwww) + _9;
    gl_Position = _9;
    pcrRainbowTintUv = (uv * _RainbowTintMask_ST.xy) + _RainbowTintMask_ST.zw;
    vec2 _109 = pcrRainbowTintUv;
    vs_TEXCOORD0 = vec4(vs_TEXCOORD0.x, vs_TEXCOORD0.y, _109.x, _109.y);
    vs_TEXCOORD0 = vec4(_99.x, _99.y, vs_TEXCOORD0.z, vs_TEXCOORD0.w);
    _9.x = dot(_116, _WorldToObject[0].xyz);
    _9.y = dot(_116, _WorldToObject[1].xyz);
    _9.z = dot(_116, _WorldToObject[2].xyz);
    _138 = dot(_9.xyz, _9.xyz);
    _138 = inversesqrt(_138);
    vs_TEXCOORD2 = vec3(_138) * _9.xyz;
    pcrRainbowUv = (uv * _RainbowTex_ST.xy) + _RainbowTex_ST.zw;
    vec2 _161 = pcrRainbowUv;
    vs_TEXCOORD3 = vec4(_161.x, _161.y, vs_TEXCOORD3.z, vs_TEXCOORD3.w);
    pcrRainbowOutlineUv = (uv * _RainbowOutlineTex_ST.xy) + _RainbowOutlineTex_ST.zw;
    vec2 _173 = pcrRainbowOutlineUv;
    vs_TEXCOORD3 = vec4(vs_TEXCOORD3.x, vs_TEXCOORD3.y, _173.x, _173.y);
    pcrRainbowBgUv = (uv * _RainbowBGTex_ST.xy) + _RainbowBGTex_ST.zw;
    vec2 _186 = pcrRainbowBgUv;
    vs_TEXCOORD4 = vec4(_186.x, _186.y, vs_TEXCOORD4.z, vs_TEXCOORD4.w);
    vs_TEXCOORD4 = vec4(vs_TEXCOORD4.x, vs_TEXCOORD4.y, vec2(1.0).x, vec2(1.0).y);
}
